name: Draft a release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version number (e.g. 1.2.3) OR one of: patch|minor|major|prepatch|preminor|premajor|prerelease'
        required: true
        default: 'patch'

jobs:
  draft-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/python-poetry-env
      - name: Update version
        id: updated_version
        shell: bash
        env:
          REQUESTED_VERSION: ${{ github.event.inputs.version }}
        run: |
          poetry version "$REQUESTED_VERSION"
          version=$(poetry version --short)
          echo ::set-output name="version::$version"
      - name: Update changelog
        id: changelog
        shell: bash
        env:
          RELEASE_VERSION: ${{ steps.updated_version.outputs.version }}
        run: |
          poetry run kacl-cli release "$RELEASE_VERSION" --modify --auto-link
          echo "" >> CHANGELOG.md
          body=$(poetry run kacl-cli get "$RELEASE_VERSION")
          body="${body//'%'/'%25'}"
          body="${body//$'\n'/'%0A'}"
          body="${body//$'\r'/'%0D'}"
          echo ::set-output name="body::$body"
      - name: Commit changes
        uses: EndBug/add-and-commit@8c12ff729a98cfbcd3fe38b49f55eceb98a5ec02 # v7
        with:
          add: 'CHANGELOG.md pyproject.toml'
          message: 'Release ${{ steps.updated_version.outputs.version }}'
      - name: Create tag
        env:
          RELEASE_VERSION: ${{ steps.updated_version.outputs.version }}
        run: |
          git tag "$RELEASE_VERSION"
          git push origin "$RELEASE_VERSION"
      - name: Create a draft release
        uses: actions/create-release@0cb9c9b65d5d1901c1f53e5e66eaf4afd303e70e # v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.updated_version.outputs.version }}
          release_name: Release ${{ steps.updated_version.outputs.version }}
          body: ${{ steps.changelog.outputs.body }}
          draft: true
